// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbKkZqPawpYV_UWlc1vppeiJLRxbFcj0',
    appId: '1:930093809800:web:4dbaf25ce24d6fc8b5df3d',
    messagingSenderId: '930093809800',
    projectId: 'dair-notes-project',
    authDomain: 'dair-notes-project.firebaseapp.com',
    storageBucket: 'dair-notes-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHupHWN8x5g1Gxnea80RPnPE2Tp5My9I',
    appId: '1:930093809800:android:6cf52cb32ebf91efb5df3d',
    messagingSenderId: '930093809800',
    projectId: 'dair-notes-project',
    storageBucket: 'dair-notes-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHq2JWtUiKx1JUL-IxLhp1LWGW4jpE0A',
    appId: '1:930093809800:ios:23416c0307aba1d1b5df3d',
    messagingSenderId: '930093809800',
    projectId: 'dair-notes-project',
    storageBucket: 'dair-notes-project.appspot.com',
    iosClientId: '930093809800-m0p0oul0qt1s1nlp13iqkh5j3lhaj8sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
